### PR TITLE
Add JsonScript test

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
@mwjames the SMW class is not found by the autoloader. Same on my local box. Any idea what I am doing wrong?

### CODE REVIEW

**Comment by mwjames** [comment]
The JSONScript is part of the SMW test setup which why those that want access to it are expected to add the autoloader as seen here:

- https://github.com/SemanticMediaWiki/SemanticScribunto/blob/master/tests/bootstrap.php#L11-L13, https://github.com/SemanticMediaWiki/SemanticScribunto/tree/master/tests/phpunit/Integration/JSONScript

- https://github.com/SemanticMediaWiki/SemanticCite/blob/master/tests/bootstrap.php#L19-L21, https://github.com/SemanticMediaWiki/SemanticCite/tree/master/tests/phpunit/Integration/JSONScript

PS: I always wanted to isolate this but is too much work with no particular gain since it is only used with SMW or dependent extensions.

**Comment by JeroenDeDauw** [comment]
@mwjames thank you! For some reason this is still not working though. 

image

**Comment by mwjames** [comment]
> @mwjames thank you! For some reason this is still not working though.

I suspect `SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest;` isn't in the class map:

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/5dc4408170c6cdae87fadbe54a6503cd69d196d0/tests/autoloader.php#L66-L68

**Comment by JeroenDeDauw** [comment]
Looks likely. Don't see why that bootstrap.php would end up being included. It does somehow for the tests in the linked extensions?

**Comment by mwjames** [comment]
>  It does somehow for the tests in the linked extensions?

Well, SemanticCite and SematicScribunto use the `JsonTestCaseScriptRunner` but have to implement or override a couple of methods.

SemanticResultFormats uses `JsonTestCaseScriptRunnerTest` directly.

**Comment by JeroenDeDauw** [comment]
Fixed by adding loading of SMW test classes like this:

```php
$autoloader->addPsr4( 'SMW\\Tests\\', __DIR__ . '/../../SemanticMediaWiki/tests/phpunit' );
```

Should the SMW test autoloader not already do that?

**Comment by mwjames** [comment]
> Should the SMW test autoloader not already do that?

I far as I remember I created the `autoloader.php` to be included by extensions to allow acces to some of the internal SMW test classes, while SMW's `bootstrap.php` takes care of adding `$autoloader->addPsr4( 'SMW\\Tests\\'...`.

SRF actually does [0]  `$autoloader->addPsr4( 'SMW\\Tests\\'...` which is why it has access to `JsonTestCaseScriptRunnerTest`.

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/tests/bootstrap.php#L16

**Comment by JeroenDeDauw** [comment]
Great stuff is fluff now.

Not sure how to make assertions for the main output of this format though, since that is a bunch of JS stuffed into `SMWOutputs::requireScript` (https://github.com/ProfessionalWiki/ModernTimeline/blob/master/src/TimelinePresenter.php#L31-L33). That is not part of what the `"type": "parser"` tests look at. Any way to do that? If not, thoughts on how to get there?

**Comment by mwjames** [comment]
> Not sure how to make assertions for the main output of this format though, since that is a bunch of JS stuffed into SMWOutputs::requireScript (https://github.com/ProfessionalWiki/ModernTimeline/blob/master/src/TimelinePresenter.php#L31-L33). That is not part of what the "type": "parser" tests look at. Any way to do that? If not, thoughts on how to get there?

In general, to validate JS one would need a headless browser together with webdriver like https://github.com/facebook/php-webdriver.

As for the content of the `ParserOutput` or `OutputPage` instance, the `"type": "parser"` uses the prepared edit in [0] to gain access to an instance after the processing has finished and depending on how deep the MW processing chain when up to this point one may or may not have access to particular information. For example, there is a `onOutputPage` option but I'm not sure if that would help here. So maybe add a new option `use-smwoutput` to gain access to those object instances and retrieve HTML or Text from it.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/ParserTestCaseProcessor.php#L162-L164

**Comment by JeroenDeDauw** [comment]
I tried 

```php
		if ( isset( $case['assert-output']['include-head-items'] ) && $case['assert-output']['include-head-items'] ) {
			$output .= implode( '', $parserOutput->getHeadItems() );
		}
```

I'm getting the head items from all pages though, not just the one under test.

**Comment by JeroenDeDauw** [comment]
@mwjames for now I got the tests to work by just stuffing a copy of the JSON data into a hidden HTML div. https://github.com/ProfessionalWiki/ModernTimeline/blob/master/src/TimelinePresenter.php#L73-L80

Originally I actually had the JSON in a script tag inside of the HTML. This worked fine on Special:Ask but got escaped on wiki pages. Any idea how to avoid that escaping? Then I don't need to use SMWOutputs here (one less global!) and can use that JsonScript already supports.

**Comment by mwjames** [comment]
> Any idea how to avoid that escaping? Then I don't need to use SMWOutputs here (one less global!) and can use that JsonScript already supports.

You could just add the JSON as `data` attribute to the HTML element or use

```
$id = some unique identifier

SMWOutputs::requireHeadItem(
	$id,
	\Skin::makeVariablesScript(
		[
			$id => json_encode( $data )
		],
		false
	)
);
```
Add the $id the HTML element to create a reference for the JS component to have access to the config object that holds the data in the `<script>` header and then on the JS side you fetch the data via:

```
mw.config.get( `my_id` );
```

These are the two methods that come to my mind right now that are used by different result printers to transfer data to the JS component.

**Comment by JeroenDeDauw** [comment]
I am currently using `SMWOutputs::requireHeadItem`, which leads to the testing problem.

You're right I could just stuff the JSON into the HTML. That is what I do in Maps. However it seems kinda silly for the JS to have to parse the stored JSON to get at the data. That's why I opted for "real" JSON in this extension.

**Comment by mwjames** [comment]
> I am currently using SMWOutputs::requireHeadItem, which leads to the testing problem.

I quickly hacked this into the table printer

```
		$id = 'foooooo';

		\SMWOutputs::requireHeadItem(
			$id,
			\Skin::makeVariablesScript(
				[
					$id => json_encode( [ 'abc'] )
				],
				false
			)
		);
```
and followed the
```
		if ( isset( $case['assert-output']['include-head-items'] ) && $case['assert-output']['include-head-items'] ) {
			$output .= '<include-head-items>' . implode( '', $parserOutput->getHeadItems() ) . '</include-head-items>';
		}
```

The JSONScript validation with option `"include-head-items": true,` will produce something like
```
<include-head-items>              <script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"foooooo":"[\"abc\"]"});});</script>
</include-head-items>
```
It means the output is is isolated and you'll able to validate against `mw.config.set({"foooooo":"[\"abc\"]"});`.

**Comment by mwjames** [comment]
> Should the SMW test autoloader not already do that?

On the matter of "How to ..." there is now a [0] (requires SMW 3.1+) to avoid pulling in something like `$autoloader->addPsr4( 'SMW\\Tests\\', __DIR__ . '/../../SemanticMediaWiki/tests/phpunit' );`

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/docs/extension.md

**Pull request merged**
