### PR TITLE
Improve "extension.json"

### PR DESCRIPTION
**Pull request by kghbln**

### CODE REVIEW

**Comment by kghbln** [comment]
@JeroenDeDauw A squash and merge will be great if in fluff!

**Comment by kghbln** [comment]
Just saw this: https://github.com/ProfessionalWiki/ModernTimeline/releases/tag/0.1.0 Why don't we do semver with alpha, beta and rc flags rather than the quaint MW system?

**Comment by JeroenDeDauw** [comment]
I am following semver. What MW system are you referring to?

**Comment by kghbln** [comment]
> What MW system are you referring to?

Starting versioning with below zero versions. I believe that we can be confident that the 1.0.0 release is already usable. A 0.1.0 would not convey this message. Self-confidence is good, so I heard. :)

**Comment by JeroenDeDauw** [comment]
1.0 once I fixed the show stopping bugs (icon display and the thing often not loading without refresh)

**Comment by kghbln** [comment]
> 1.0 once I fixed the show stopping bugs (icon display and the thing often not loading without refresh)

Sure. :)

**Pull request merged**
